= IVP - Power - All Devices
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get Battery Details

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the xref:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/ivp/power` endpoint provides the following response data.

As of recent Gateway software versions this request requires user authentication and authorisation, see xref:../../Authentication.adoc[Authentication].

== Examples

=== Get All Battery Storage Information

unit ...0003 has flipped to positive (49000 mW, discharging slightly) while the other three are still charging 

.GET */ivp/power* Response
[source,json,subs="+quotes"]
----
{
  "devices:": [
    {
      "serial_num": "000000000001",
      "real_power_mw": -178000,
      "apparent_power_mva": -178000,
      "soc": 100
    },
    {
      "serial_num": "000000000002",
      "real_power_mw": -1033000,
      "apparent_power_mva": -1033000,
      "soc": 96
    },
    {
      "serial_num": "000000000003",
      "real_power_mw": 49000,
      "apparent_power_mva": 49000,
      "soc": 95
    },
    {
      "serial_num": "000000000004",
      "real_power_mw": -1350000,
      "apparent_power_mva": -1350000,
      "soc": 93
    }
  ]
}
----
